management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/chloe?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123abcABC
  redis:
    password: 123456
    host: 127.0.0.1
    port: 637
